fail_fast: true  # to stop running hooks after one fails
default_stages: [commit, push]

default_language_version:
    python: python3.12

repos:

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.5
    hooks:
      - id: ruff
        args: [ "--select", "I", "--fix" ]
      - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.13.0
    hooks:
      - id: mypy