services:

  app:
    build:
      context: .
      dockerfile: ./docker/local/django/Dockerfile
    image: movies_api_local_django
    container_name: movies_api_local_django
    depends_on:
      - redis
      - postgres
    volumes:
      - .:/app:z
    env_file:
      - ./local.env
    ports:
      - '8000:8000'
    command: sh -c "/start"

  postgres:
    image: postgres
    env_file:
      - local.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"

  redis:
    image: redis
    container_name: movies_api_api_local_redis
    ports:
      - '6379:6379'

volumes:
  postgres_data: