# Generated by Django 5.1.6 on 2025-02-14 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MovieRating",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, null=True, verbose_name="Updated at")),
                ("movie_id", models.UUIDField()),
                (
                    "rating_type",
                    models.CharField(
                        choices=[("UPVOTE", "Upvote"), ("DOWNVOTE", "Downvote")], default="UPVOTE", max_length=8
                    ),
                ),
            ],
        ),
    ]
